/***** DO NOT EDIT THIS FILE *****/
// MonkeyProject.js generated by MonkeyTalk

load("libs/MonkeyTalkAPI.js");


var MonkeyProject = {};

/*** script -- KTest ***/
MonkeyProject.KTest = function(app) {
	MT.Script.call(this, app, "KTest.mt");
};

MonkeyProject.KTest.prototype = new MT.Script;

MonkeyProject.KTest.prototype.call = function() {
	//run: KTest.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.kTest = function() {
	return new MonkeyProject.KTest(this);
};

